name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install

      - name: Lint HTML files using npx
        run: npx htmlhint src/**/*.html

      - name: Lint CSS files using npx
        run: npx stylelint styles/**/*.css

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Parcel globally
        run: npm install -g parcel

      - name: Build website using Parcel
        run: parcel build src/*.html 

      - name: Ensure build success
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed, dist directory not found!"
            exit 1
          fi
