name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install -g htmlhint stylelint
      - name: Lint HTML files
        run: htmlhint src/**/*.html
      - name: Lint CSS files
        run: stylelint styles/**/*.css

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build website using Parcel
        run: parcel build src/*.html